# Generated by Django 4.1.7 on 2023-04-03 12:09

from django.db import migrations, models
import fileupload.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fileload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50, validators=[fileupload.models.validate_model])),
                ('file', models.FileField(upload_to='<django.db.models.fields.CharField>_files', verbose_name='excel File')),
            ],
            options={
                'ordering': ['file'],
            },
        ),
    ]
