version: '3'

services:
  # Database
  database:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    env_file:
      - ./.db.dev.env
    networks:
      - back
  # API
  api:
    build: ../backend/python
    volumes:
      - static_volume:/opt/app/api/staticfiles
      - media_volume:/opt/app/api/mediafiles
    restart: always
    env_file:
      - ./.server.dev.env
    depends_on:
      - database
    networks:
      - front
      - back

volumes:
  postgres_data: 
  static_volume:
  media_volume:


networks:
  front:
    driver: bridge
  back:
    driver: bridge
  docker-network:
    driver: bridge