# Generated by Django 4.2 on 2023-04-08 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('structure', models.CharField(max_length=200)),
                ('sigle', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=50)),
                ('adresse', models.CharField(max_length=100)),
                ('commune', models.CharField(max_length=100)),
                ('localisation', models.CharField(max_length=100)),
                ('domaine_intervention', models.CharField(blank=True, max_length=100)),
                ('GPS', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['structure'],
            },
        ),
    ]
